spring:
  application:
    name: 4vidia-config

  cloud:
    config:
      server:
        git:
          uri: git@github.com:nhnacademy-be12-4vidia/config-repo.git
          private-key: ${SSH_PRIVATE_KEY}


  security:
    user:
      name: ${ADMIN_ID}
      password: ${ADMIN_PASSWORD}

server:
  port: 8080

